- name: "🔥 priority: high"
  description: "Tasks with high priority that require immediate attention."
  color: "FF5733"
- name: "⚠️ priority: medium"
  description: "Medium priority tasks that should be addressed soon."
  color: "FFC300"
- name: "🕒 priority: low"
  description: "Low priority tasks that can be postponed for the future."
  color: "C4C4C4"
- name: "🐞 bug"
  description: "An error that needs fixing."
  color: "FF5733"
- name: "⚡ performance"
  description: "Optimization of system or code performance."
  color: "FFC107"
- name: "🔒 security"
  description: "Vulnerabilities or issues related to security."
  color: "DC3545"
- name: "✂️ duplicate"
  description: "Duplicate of an existing task or issue."
  color: "FF5733"
- name: "🚫 wontfix"
  description: "The issue will not be fixed; the task is closed."
  color: "DC3545"
- name: "❓ invalid"
  description: "Invalid task, lacking sufficient information or incorrect format."
  color: "C4C4C4"
- name: "🚀 enhancement"
  description: "Improvement or addition of a new feature."
  color: "28A745"
- name: "💡 feature request"
  description: "Request for a new feature or enhancement."
  color: "FF851B"
- name: "📚 documentation"
  description: "Tasks related to updating or improving documentation."
  color: "007BFF"
- name: "🛠️ refactor"
  description: "Refactoring code without adding new functionality."
  color: "6F42C1"
- name: "✅ test"
  description: "Related to testing and verification of code."
  color: "20C997"
- name: "🚧 in progress"
  description: "Task currently being worked on."
  color: "FFC300"
- name: "👀 needs review"
  description: "Requires code or changes review."
  color: "17A2B8"
- name: "🗣️ needs feedback"
  description: "Comments or feedback needed from the community or team."
  color: "6C757D"
- name: "🕹️ on hold"
  description: "Task temporarily on hold."
  color: "C4C4C4"
- name: "🟢 easy"
  description: "Easy task that can be completed quickly."
  color: "28A745"
- name: "🟡 medium"
  description: "Task of medium difficulty requiring moderate effort."
  color: "FFC300"
- name: "🔴 hard"
  description: "Difficult task requiring significant resources and time."
  color: "DC3545"
- name: "🧹 chore"
  description: "Routine tasks, maintenance, or non-user-facing changes."
  color: "FAD8C7"
- name: "🛠️ maintenance"
  description: "Tasks related to technical debt, infrastructure upkeep."
  color: "FFD700"
- name: "⚙️ infrastructure"
  description: "Tasks for maintaining or improving system infrastructure."
  color: "B0C4DE"
- name: "⚠️ triage"
  description: "A label used to categorize issues for prioritization and organization."
  color: "6C757D"
